opensearch:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/rsa
    ansible_ssh_user: ubuntu
    host_key_checking: false
    ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  children:
    os-cluster:
      hosts:
        os0:
          ansible_host: 3.82.154.205
          ip: 172.31.80.50
          roles: data,master
        os1:
          ansible_host: 44.206.231.208
          ip: 172.31.95.254
          roles: data,ingest
        os2:
          ansible_host: 3.92.133.188
          ip: 172.31.87.59
          roles: data,ingest
    master:
      hosts:
        os0: {}
    dashboards:
      hosts:
        os0: {}

