opensearch:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/rsa
    ansible_ssh_user: ubuntu
    host_key_checking: false
    ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  children:
    os-cluster:
      hosts:
        os0:
          ansible_host: 54.227.20.111
          ip: 172.31.23.244
          roles: data,master
        os1:
          ansible_host: 54.227.44.3
          ip: 172.31.27.43
          roles: data,ingest
        os2:
          ansible_host: 34.229.166.103
          ip: 172.31.30.40
          roles: data,ingest
    master:
      hosts:
        os0: {}
    dashboards:
      hosts:
        os0: {}
