opensearch:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/rsa
    ansible_ssh_user: ubuntu
    host_key_checking: false
    ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  children:
    os-cluster:
      hosts:
        os0:
          ansible_host: 44.211.69.70
          ip: 172.31.82.112
          roles: data,master
        os1:
          ansible_host: 52.54.231.134
          ip: 172.31.93.190
          roles: data,ingest
        os2:
          ansible_host: 3.87.184.138
          ip: 172.31.93.104
          roles: data,ingest
    master:
      hosts:
        os0: {}
    dashboards:
      hosts:
        os0: {}

