---
# defaults file for roles/logging/fluent-bit
service_name: fluent-bit
fb_user: fluent-bit
config_dir: /etc/fluent-bit

fluentbit_apt_key_url: "https://packages.fluentbit.io/fluentbit.key"
fluentbit_apt_key_path: "/usr/share/keyrings/fluentbit-keyring.gpg"
fluentbit_apt_repos_url: "https://packages.fluentbit.io/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}"
fluentbit_apt_repos_component: "main"
fluentbit_pkg_name: "fluent-bit"
fluentbit_pkg_version: "{{ fluentbit_version | default('') }}" # For retro-compatibility
fluentbit_svc_name: "fluent-bit"
fluentbit_svc_limit_open_files: 65536

##--
## Main configuration
##--
fluentbit_service_flush_seconds: 5
fluentbit_service_daemon: false
fluentbit_service_custom_parsers_file: []
fluentbit_service_log_level: info
fluentbit_service_enable_metrics: false
fluentbit_service_metrics_listen_ip: 0.0.0.0
fluentbit_service_metrics_listen_port: 2020

# Default inputs
fluentbit_inputs: []

# Default filters
fluentbit_filters: []

# Default outputs
fluentbit_outputs: []

fluentbit_additional_conf_files: []
