---
# tasks file for ansible/roles/logging/docker-logging-driver
- name: Copy Docker daemon config templates
  template:
    src: daemon.json
    dest: /etc/docker/
    backup: yes

- name: Install Fluent-bit docker driver
  shell: docker plugin install grafana/loki-docker-driver:{{ loki_version }} --alias loki --grant-all-permissions
  ignore_errors: true

- name: config docker
  template:
    src: daemon.json
    dest: /etc/docker/
    mode: "0600"
    backup: yes
  notify: restart docker
