---
# tasks file for ansible/roles/logging/docker-logging-driver
- name: Configure docker daemon to send containers log to fluent-bit
  template:
    src: daemon.json
    dest: /etc/docker/
    mode: "0600"
    backup: yes
  notify: restart docker
