opensearch:
  children:
    os-cluster:
      hosts:
%{ for i, val in instance ~}
        os${i}:
          ansible_host: ${val.public_ip}
          ip: ${val.private_ip}
          roles: ${val.roles}
%{ endfor ~}
    master:
      hosts:
        os0: {}
    dashboards:
      hosts:
        os0: {}
